/*
 * Palm (Wrestler GPU, CHIP_PALM, Evergreen / TeraScale-2 VLIW5) image
 * atomic RAT ops never signal the returning-atomic completion handshake.
 * The CP ring stalls indefinitely until the kernel soft-reset fires
 * (W8.a/b/c recovery path, 10 s lockup_timeout per stall).  W8 is
 * recovery infrastructure, not prevention.
 *
 * This check scans a NIR shader for any image atomic intrinsic and
 * returns true when such an intrinsic is present on CHIP_PALM.  The
 * pipeline-creation path treats true as VK_ERROR_FEATURE_NOT_PRESENT,
 * blocking the wedge at pipeline compile time rather than at dispatch.
 *
 * VK_FORMAT_FEATURE_2_STORAGE_IMAGE_ATOMIC_BIT is already cleared for
 * CHIP_PALM by terakan_GetPhysicalDeviceFormatProperties2, so conformant
 * applications that query format features before creating storage images
 * will never reach this point with a shader containing image atomics.
 * This check is the backstop for applications that skip format queries
 * or custom test shaders that ignore format feature results.
 *
 * Intrinsics covered (generated by the `image()` macro in
 * nir_intrinsics.py for the `atomic` and `atomic_swap` names):
 *   nir_intrinsic_image_deref_atomic         (deref / variable-index path)
 *   nir_intrinsic_image_deref_atomic_swap    (deref / variable-index path)
 *   nir_intrinsic_image_atomic               (index path)
 *   nir_intrinsic_image_atomic_swap          (index path)
 *   nir_intrinsic_bindless_image_atomic      (bindless handle path)
 *   nir_intrinsic_bindless_image_atomic_swap (bindless handle path)
 *   nir_intrinsic_image_heap_atomic          (heap-index path)
 *   nir_intrinsic_image_heap_atomic_swap     (heap-index path)
 */

#include "terakan_nir.h"

#include "amd_family.h"
#include "nir.h"
#include "nir_intrinsics.h"

/* Returns true when the shader contains any image atomic intrinsic and
 * chip_family is CHIP_PALM.  The caller must propagate
 * VK_ERROR_FEATURE_NOT_PRESENT when this returns true.
 *
 * Must run BEFORE terakan_nir_lower_bindings, which replaces these
 * intrinsics with R600-specific UAV intrinsics and removes the
 * originals. */
bool
terakan_nir_palm_image_atomic_reject_check(nir_shader const * const nir,
                                           enum radeon_family const chip_family)
{
   if (chip_family != CHIP_PALM)
      return false;

   nir_foreach_function_impl(impl, nir) {
      nir_foreach_block(block, impl) {
         nir_foreach_instr(instr, block) {
            if (instr->type != nir_instr_type_intrinsic)
               continue;
            nir_intrinsic_instr const * const intr = nir_instr_as_intrinsic(instr);
            switch (intr->intrinsic) {
            case nir_intrinsic_image_deref_atomic:
            case nir_intrinsic_image_deref_atomic_swap:
            case nir_intrinsic_image_atomic:
            case nir_intrinsic_image_atomic_swap:
            case nir_intrinsic_bindless_image_atomic:
            case nir_intrinsic_bindless_image_atomic_swap:
            case nir_intrinsic_image_heap_atomic:
            case nir_intrinsic_image_heap_atomic_swap:
               return true;
            default:
               break;
            }
         }
      }
   }
   return false;
}
