# SPDX-License-Identifier: MIT
"""Source-header audit for the R3V lane.

A header carries the license grant and the file's own description.  Three
rules fix that content, and each one fails closed.

An SPDX-License-Identifier line states the grant, so every C, header, and
Python file under the audited root carries one within its opening lines.

A copyright line asserts that a named holder holds the copyright, so it
appears only for a holder who does.  The names a template supplies -- the
local git identity, a model's default, an invented project collective --
assert authorship that does not exist, and absent attribution is the correct
state for a file with no such holder.  REAL_COPYRIGHT_HOLDERS is the reviewed
list of holders whose lines this tree preserves verbatim; it is empty because
every file under this root is written here, and a file arriving with an
upstream header joins the list by review.

AI participation rides in commit trailers (Assisted-by, Generated-by), so a
header naming a model or a generation tool states it in the wrong artifact.

Modes:
  <root>...        audit every C, header, and Python file under each root
  --fixture NAME   audit one synthetic file carrying the NAME defect, which
                   calibrates each rule against a header known to violate it
  --selftest       every fixture, plus the clean header each one mutates
"""

import re
import sys
import tempfile
from pathlib import Path

SUFFIXES = (".c", ".h", ".py")

# Lines a header may carry that name a holder.  Each entry is a holder this
# tree preserves verbatim because they hold the copyright on a file that came
# from elsewhere.
REAL_COPYRIGHT_HOLDERS: tuple[str, ...] = ()

# The opening lines a header rule reads.  A license grant and a copyright line
# sit at the top of a file; a match further down is prose or test data.
HEADER_LINES = 8

COPYRIGHT = re.compile(r"^[^A-Za-z0-9]*Copyright\b(?P<holder>.*)$",
                       re.IGNORECASE)

# Disclosure that belongs in a commit trailer.  The pattern matches the tool
# naming that reaches a header, not the words themselves: "generated from
# vk.xml by <script>" states a build mechanism and stays.
AI_DISCLOSURE = re.compile(
    r"\b(LLM[- ]assisted|AI[- ]assisted|generated by (claude|chatgpt|codex|"
    r"copilot|gemini|gpt|an? (AI|LLM)))\b", re.IGNORECASE)


def audit_file(path: Path):
    """Return the defects in one file's header."""
    try:
        head = path.read_text(errors="replace").splitlines()[:HEADER_LINES]
    except OSError as exc:
        return [f"{path}: unreadable: {exc}"]

    defects = []
    if not any("SPDX-License-Identifier" in line for line in head):
        defects.append(f"{path}: no SPDX-License-Identifier in the first "
                       f"{HEADER_LINES} lines")
    for line in head:
        match = COPYRIGHT.match(line.strip())
        if match is not None:
            holder = match.group("holder").strip()
            if not any(real in holder for real in REAL_COPYRIGHT_HOLDERS):
                defects.append(f"{path}: copyright line names an unreviewed "
                               f"holder: {line.strip()}")
        if AI_DISCLOSURE.search(line):
            defects.append(f"{path}: AI disclosure belongs in a commit "
                           f"trailer: {line.strip()}")
    return defects


def audit_roots(roots):
    """Audit every source file under each root, newest defect list first."""
    defects = []
    audited = 0
    for root in roots:
        root = Path(root)
        files = ([root] if root.is_file() else
                 sorted(p for p in root.rglob("*") if p.suffix in SUFFIXES))
        for path in files:
            audited += 1
            defects.extend(audit_file(path))
    return audited, defects


# A clean header and the three mutations of it, each violating one rule.  The
# audit runs over the written file, so a rule that stopped reading its line
# passes its own fixture.
CLEAN_HEADER = """\
/* SPDX-License-Identifier: MIT */

/* A description of the mechanism this file carries. */
"""

FIXTURES = {
    "missing-spdx": CLEAN_HEADER.replace(
        "/* SPDX-License-Identifier: MIT */\n", ""),
    "invented-copyright": CLEAN_HEADER.replace(
        "/* SPDX-License-Identifier: MIT */",
        "/* SPDX-License-Identifier: MIT\n"
        " * Copyright (c) 2026 the example project\n */"),
    "ai-disclosure": CLEAN_HEADER.replace(
        "/* SPDX-License-Identifier: MIT */",
        "/* SPDX-License-Identifier: MIT\n"
        " * Generated by Claude\n */"),
}


def run_fixture(name, contents=None):
    """Audit one synthetic header and report its defects."""
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "fixture.c"
        path.write_text(FIXTURES[name] if contents is None else contents)
        _, defects = audit_roots([path])
    print(f"header fixture {name}: {len(defects)} defects")
    for defect in defects:
        print(f"  {defect}")
    return 1 if defects else 0


def selftest():
    assert run_fixture("clean", CLEAN_HEADER) == 0
    for name in sorted(FIXTURES):
        assert run_fixture(name) == 1, name
    print(f"r3v_source_header_audit selftest: {len(FIXTURES)} defect legs "
          f"and one clean leg OK")
    return 0


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if argv[:1] == ["--selftest"]:
        return selftest()
    if argv[:1] == ["--fixture"]:
        if argv[1] == "missing-root":
            # The dropped-subtree calibration: one absent root beside a
            # resolvable file must refuse through the same per-root check
            # the real audit runs, never report a clean scan of the rest.
            return main([__file__, "does-not-exist-root"])
        return run_fixture(argv[1],
                           CLEAN_HEADER if argv[1] == "clean" else None)

    # A root that resolves to nothing reports a clean audit it never ran,
    # so every requested root must exist and contribute at least one file
    # before the aggregate verdict counts.
    missing = [root for root in argv
               if not Path(root).exists() or
               (Path(root).is_dir() and
                not any(p.suffix in SUFFIXES for p in Path(root).rglob("*")))]
    if missing:
        for root in missing:
            print(f"model failure: root {root} is absent or contributes "
                  f"no source files")
        return 2

    audited, defects = audit_roots(argv)
    for defect in defects:
        print(defect)
    print(f"source headers: {audited} audited, {len(defects)} defects")
    if audited < 20:
        print(f"model failure: {audited} files audited, too few for the "
              f"R3V lane; the roots did not resolve")
        return 2
    return 1 if defects else 0


if __name__ == "__main__":
    sys.exit(main())
