#!/bin/sh
# Regenerate r3v_typed_carry_spirv.h from the checked-in typed-carry corpus
# vertex shaders.  Each module is the recur90 over-budget chain plus one typed
# head whose transport class the R2VB producer plan must select or decline;
# the GLSL sources are the fixtures of record and the header is their SPIR-V
# form, checked in so the oracle builds without a build-time glslang
# dependency.  Requires glslangValidator (glslang) on PATH.
set -eu
cd "$(dirname "$0")"
out=r3v_typed_carry_spirv.h
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# SPIR-V binary words are little-endian.  Reading one-byte units keeps the
# generated values independent of the host byte order used by od.
emit_spirv_words()
{
  od -An -tx1 -v "$1" |
    awk '{
      for (i = 1; i <= NF; i++) {
        bytes[++byte_in_word] = $i
        byte_count++
        if (byte_in_word == 4) {
          if (word_in_line == 0)
            printf "   "
          else
            printf " "
          printf "0x%s%s%s%s,", bytes[4], bytes[3], bytes[2], bytes[1]
          word_in_line++
          if (word_in_line == 4) {
            printf "\n"
            word_in_line = 0
          }
          byte_in_word = 0
        }
      }
    }
    END {
      if (byte_count == 0 || byte_in_word != 0)
        exit 1
      if (word_in_line != 0)
        printf "\n"
    }'
}
{
  printf '/*\n'
  printf ' * SPDX-License-Identifier: MIT\n */\n\n'
  printf '/* Generated by gen_spirv_fixtures.sh from the typed-carry corpus\n'
  printf ' * vertex shaders in this directory (glslangValidator -V).  Each\n'
  printf ' * module is the recur90 over-budget chain plus one typed head; the\n'
  printf ' * GLSL sources are the fixtures of record. */\n\n'
  printf '#ifndef R3V_TYPED_CARRY_SPIRV_H\n#define R3V_TYPED_CARRY_SPIRV_H\n\n'
  printf '#include <stdint.h>\n#include <stddef.h>\n\n'
  for v in t_*.vert; do
    name=$(basename "$v" .vert)
    glslangValidator -V "$v" -o "$tmp/$name.spv" >/dev/null
    printf 'static const uint32_t %s_spirv[] = {\n' "$name"
    emit_spirv_words "$tmp/$name.spv"
    printf '};\n'
    printf '\n'
  done
  # SPIR-V assembly fixtures of record: the assembly pins the exact
  # representation (select-versus-branch, boolean lifetime), so it
  # reassembles with spirv-as and validates with spirv-val.
  for a in t_*.spvasm; do
    [ -e "$a" ] || continue
    name=$(basename "$a" .spvasm)
    spirv-as "$a" -o "$tmp/$name.spv"
    spirv-val "$tmp/$name.spv"
    printf 'static const uint32_t %s_spirv[] = {\n' "$name"
    emit_spirv_words "$tmp/$name.spv"
    printf '};\n'
    printf '\n'
  done
  printf '#endif /* R3V_TYPED_CARRY_SPIRV_H */\n'
} > "$out"
echo "wrote $out"
