#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate r300_display_reg.h from the MIT-licensed X.Org DDX radeon_reg.h.

The display controller (CRTC1/CRTC2) and the OV0 overlay engine have no
register definitions anywhere in mesa: r300_reg.h is deliberately pure 3D
(mirroring the kernel's r300_reg.h / radeon_reg.h split).  The wsi-drm
presentation lane and any future OV0 backend need the scanout register names,
and the only MIT-licensed source carrying them is the X.Org DDX header
(xf86-video-ati radeon_reg.h, Copyright 2000 ATI Technologies Inc. and
VA Linux Systems Inc., MIT).  The kernel's radeon_reg.h carries the same
names under GPL and must not be used as a source for mesa defines.

Extraction is mechanical so the output regenerates when the source moves:

* a register is a column-0 "#define NAME 0xNNNN" line;
* a field belongs to the register definition it follows (positional
  ownership, the same convention the DDX file itself uses: indented
  "#<tab/spaces>define" lines sit directly under their register);
* three curated groups are emitted: CRTC1 (RADEON_CRTC_*), CRTC2
  (RADEON_CRTC2_*), and OV0 (RADEON_OV0_*) minus the four-tap filter
  coefficient and gamma-ramp blocks, which are withheld until a consumer
  exercises them.

Canonical source path (steinmarder evidence vendoring):
  steinmarder/src/re/radeon/sources/xorg_ddx_radeon_reg.h

Usage:
  r300_display_reg_gen.py <xorg_ddx_radeon_reg.h> <output.h> [r300_reg.h]

The optional third argument enables the collision self-check against the 3D
register header the output is designed to sit beside.
"""

import re
import sys

REGISTER_RE = re.compile(r"^#define\s+(\w+)\s+(0x[0-9a-fA-F]+)\b(.*)$")
FIELD_RE = re.compile(r"^#\s+define\s+(\w+)")

CRTC1_PREFIX = "RADEON_CRTC_"
CRTC2_PREFIX = "RADEON_CRTC2_"
OV0_PREFIX = "RADEON_OV0_"

# Withheld OV0 sub-blocks: scaler filter taps and the gamma ramp.  Both are
# coefficient tables with no current consumer; keeping the emitted surface to
# registers a present/flip/overlay path actually programs keeps review
# tractable.  Regenerate with these prefixes removed when a consumer lands.
WITHHELD_PREFIXES = (
    "RADEON_OV0_FOUR_TAP_COEF_",
    "RADEON_OV0_GAMMA_",
)

# CRTC2 is 12 unique registers: the DDX header defines RADEON_CRTC2_STATUS
# twice at the same offset and the extractor deduplicates by name.
EXPECTED_GROUP_COUNTS = {"CRTC1": 16, "CRTC2": 12, "OV0": 44}

HEADER = """\
/*
 * Copyright 2000 ATI Technologies Inc., Markham, Ontario, and
 *                VA Linux Systems Inc., Fremont, California.
 *
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation on the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the
 * next paragraph) shall be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON-INFRINGEMENT.  IN NO EVENT SHALL ATI, VA LINUX SYSTEMS AND/OR
 * THEIR SUPPLIERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/* Display controller and OV0 overlay registers for r300-class silicon.
 *
 * GENERATED by r300_display_reg_gen.py from the MIT-licensed X.Org DDX
 * radeon_reg.h -- edit the generator and regenerate, do not hand-edit.
 * r300_reg.h stays pure 3D-pipe; the scanout plane lives here.
 *
 * Register semantics cross-reference (names only, no text copied):
 *   - CRTC timing/offset/pitch: the M56 OEM Register Reference Guide is the
 *     closest published reference for the RS485M IGP display block, and
 *     the RS690 RRG carries the fullest display-controller chapters.
 *   - RADEON_CRTC_OFFSET__GUI_TRIG_OFFSET / __OFFSET_LOCK page-flip
 *     semantics: the kernel implements the flip in r100_page_flip
 *     (drivers/gpu/drm/radeon/r100.c), retargeting scanout by writing
 *     CRTC_OFFSET with the GUI-trigger bit.
 *   - OV0 overlay: no public RRG documents the overlay engine; the DDX and
 *     kernel radeon_reg.h are the only field-level references.
 */

#ifndef R300_DISPLAY_REG_H
#define R300_DISPLAY_REG_H

"""

FOOTER = "\n#endif /* R300_DISPLAY_REG_H */\n"


def parse_blocks(source_lines):
    """Map register name -> (offset, [verbatim define lines])."""
    blocks = {}
    order = []
    current = None
    for raw in source_lines:
        line = raw.rstrip()
        reg = REGISTER_RE.match(line)
        if reg:
            name, offset, _trailing = reg.groups()
            # Re-emit the register line normalized (name + offset only) so
            # source-side trailing comments cannot smuggle non-register text.
            current = name
            if name not in blocks:
                blocks[name] = (offset, ["#define %-39s %s" % (name, offset)])
                order.append(name)
            continue
        if current and FIELD_RE.match(line):
            blocks[current][1].append(line)
    return blocks, order


def in_group(name):
    if name.startswith(CRTC2_PREFIX):
        return "CRTC2"
    if name.startswith(CRTC1_PREFIX):
        return "CRTC1"
    if name.startswith(OV0_PREFIX):
        if any(name.startswith(p) for p in WITHHELD_PREFIXES):
            return None
        return "OV0"
    return None


def main():
    if len(sys.argv) not in (3, 4):
        sys.exit(__doc__)
    src_path, out_path = sys.argv[1], sys.argv[2]
    collision_path = sys.argv[3] if len(sys.argv) == 4 else None

    with open(src_path, encoding="utf-8", errors="replace") as f:
        blocks, order = parse_blocks(f.readlines())

    groups = {"CRTC1": [], "CRTC2": [], "OV0": []}
    for name in order:
        group = in_group(name)
        if group:
            groups[group].append(name)

    for group, expected in EXPECTED_GROUP_COUNTS.items():
        actual = len(groups[group])
        assert actual == expected, (
            "%s register count %d != expected %d -- the source layout moved; "
            "re-audit the group before regenerating" % (group, actual, expected)
        )

    emitted_names = set()
    field_count = 0
    out = [HEADER]
    titles = {
        "CRTC1": "CRTC1: primary display controller (timing, scanout offset, pitch)",
        "CRTC2": "CRTC2: secondary display controller",
        "OV0": "OV0: video overlay engine (position, scale, buffers, flip, keying)",
    }
    for group in ("CRTC1", "CRTC2", "OV0"):
        out.append("/* %s */\n\n" % titles[group])
        for name in sorted(groups[group], key=lambda n: int(blocks[n][0], 16)):
            offset, lines = blocks[name]
            for line in lines:
                define_name = (REGISTER_RE.match(line) or FIELD_RE.match(line)).group(1)
                if define_name in emitted_names:
                    continue
                emitted_names.add(define_name)
                if FIELD_RE.match(line):
                    field_count += 1
                out.append(line + "\n")
        out.append("\n")

    if collision_path:
        with open(collision_path, encoding="utf-8", errors="replace") as f:
            existing = set(re.findall(r"^#\s*define\s+(\w+)", f.read(), re.M))
        collisions = emitted_names & existing
        assert not collisions, "name collisions with %s: %s" % (
            collision_path, sorted(collisions))

    out.append(FOOTER)
    with open(out_path, "w", encoding="utf-8") as f:
        f.writelines(out)

    reg_count = sum(len(v) for v in groups.values())
    print("emitted %d registers + %d fields = %d defines -> %s"
          % (reg_count, field_count, reg_count + field_count, out_path))


if __name__ == "__main__":
    main()
